---
- name: Install samba packages from OS
  apt:
    pkg:
      - krb5-config
      - krb5-user
      - libnss-winbind
      - libpam-winbind
      - winbind
      - samba
      - smbclient
      - ldb-tools
      - samba-common

