- name: creates sambadc_printers
  set_fact: 
    sambadc_printers: []

- name: creates printers_from_csv
  set_fact: 
    printers_from_csv: "{{ sambadc_csv_printers.split('\n') }}"

- name: monta lista de dicionários sambadc_printers
  set_fact: 
    sambadc_printers: > 
      {{ sambadc_printers + [{ 
        'name': item.split(',')[0]
      }]}}
  with_items: 
    - "{{ printers_from_csv }}"

- name: Creates directory /var/spool/samba
  file:
    path: /var/spool/samba
    state: directory
    owner: root
    group: root
    mode: '0777'
    recurse: yes
