---
- name: set smb.conf dinamically
  template:
    src=smb.conf.j2
    dest=/etc/samba/smb.conf
    owner=root
    group=root
    mode=0644
    validate='testparm -s %s'
  notify:
    - restart samba-ad-dc
  when: not sambadc_static

- name: use a fixed smb.conf
  template:
    src="smb.static.conf.j2"
    dest=/etc/samba/smb.conf
    owner=root
    group=root
    mode=0644
    validate='testparm -s %s'
  notify:
    - restart samba-ad-dc
  when: sambadc_static

 
