#!/bin/sh
#
# Copyright (C) Matthieu Patou <mat@matws.net> 2010-2011

TARGETDIRS="/var/lib/samba/private /var/lib/samba/sysvol /etc/samba"
WHERE=/var/backups/samba-dc
WHEN=`date +%Y-%m-%d`	# ISO 8601 standard date.
DAYS=90

mkdir -p $WHERE
 
# to set: setdomainsid XXXXXX
/usr/bin/net getdomainsid > /tmp/domainsid

for tdir in $TARGETDIRS;do
    mkdir -p $WHERE/$WHEN
    cd `dirname $tdir`
    d=`basename $tdir`
    relativedirname=`find . -type d -name "$d" -prune`
    if [ "$relativedirname" = "" ]; then
        echo 'break!'
        break
    fi
 
    n=`echo $tdir|sed 's|\/|_|g'|sed 's/^_//'`
    if [ "$d" = "private" ]; then
        find $relativedirname -name "*.ldb.bak" -exec rm {} \;
        for ldb in `find $relativedirname -name "*.ldb"`; do
            tdbbackup $ldb
            if [ $? -ne 0 ]; then
                echo "Error while backuping $ldb"
                exit 1
            fi
        done
        find $relativedirname -name "*.tdb.bak" -exec rm {} \;
        for ldb in `find $relativedirname -name "*.tdb"`; do
            #tdbbackup $ldb
            if [ $? -ne 0 ]; then
                echo "Error while backuping $ldb"
                exit 1
            fi
        done
        tar --exclude="*.ldb" --exclude="*.tdb" -cjf ${WHERE}/${WHEN}/samba4_${n}.${WHEN}.tar.bz2  $relativedirname --xattrs --warning=no-file-ignored --transform 's/.ldb.bak$/.ldb/' --transform 's/.tdb.bak$/.tdb/'

        if [ $? -ne 0 ]; then
            echo "Error while archiving ${WHERE}/${WHEN}/samba4_${n}.${WHEN}.tar.bz2"
            exit 1
        fi
        find $relativedirname -name "*.ldb.bak" -exec rm {} \;
        find $relativedirname -name "*.tdb.bak" -exec rm {} \;
    else
        tar cjf ${WHERE}/${WHEN}/samba4_${n}.${WHEN}.tar.bz2  $relativedirname --xattrs
        if [ $? -ne 0 ]; then
            echo "Error while archiving ${WHERE}/${WHEN}/samba4_${n}.${WHEN}.tar.bz2"
            exit 1
        fi
    fi
done

tdir="/var/lib/samba"
cd `dirname $tdir`
d=`basename $tdir`
relativedirname=`find . -type d -name "$d" -prune`
find $relativedirname -name "*.tdb.bak" ! -path private/* -exec rm {} \;
for ldb in `find $relativedirname -name "*.tdb"`; do
    tdbbackup $ldb
    if [ $? -ne 0 ]; then
        echo "Error while backuping $ldb"
        exit 1
    fi
done
n=`echo $tdir|sed 's|\/|_|g'|sed 's/^_//'`
tar -cjf ${WHERE}/${WHEN}/samba4_${n}.${WHEN}.tar.bz2  $relativedirname/*.tdb.bak --xattrs --warning=no-file-ignored --transform 's/.tdb.bak$/.tdb/'

find $WHERE -name "samba4_*bz2" -mtime +$DAYS -exec rm  {} \;
find "/var/lib/samba" -name "*.tdb.bak" -exec rm {} \;
